### ISSUE TITLE
Add onChangeHandler

### ISSUE THREAD

**Issue by bruceharrison1984** [bruceharrison1984/Schedulely#92]
**Describe the solution you'd like**
A user definable handler should be added that fires whenever the month/year on the calendar is changed. This could be used to dynamically fetch events for the next state of the calendar.as it stands right now, all events are expected to be fetched without respect to the current visible month.

**Comment by scottlovegrove** [comment]
Isn't this what the `onMonthChangeClick` handler is for? I was going to look at implementing this until I realised this might already exist. Or do you mean something more granular, like, if July is visible, then the handler would return 1st July (to represent the month)?

**Comment by bruceharrison1984** [comment]
You're correct, I had forgotten I had already implemented this 😄. Perhaps a better name would be appropriate.
