### ISSUE TITLE
Events passed to DayComponent aren't recalculated if events change but month stays the same

### ISSUE THREAD

**Issue by scottlovegrove** [bruceharrison1984/Schedulely#95]
**Describe the bug**
If I have a set of events that I'm passing through to the calendar, that includes, say, 2 events for a particular day, two events get passed through to the DayComponent, this is correct. If, however, I change the list of events (through some other filtering outside of the Calendar component), but the month doesn't change, and this removes one of the events for that particular day, the two original events are still passed through. 

**To Reproduce**
1. Pass in two events to the calendar for the same day
2. Have some function that reduces that array to just one event
3. Check what events are passed through to the DayComponent.

**Expected behavior**
If events are removed from the Calendar, they should not show. 

**Screenshots**
![image](https://github.com/bruceharrison1984/Schedulely/assets/25244878/efc33b4f-0181-4bb3-9a4d-7be678243e35)
This screenshot shows two events for July 28, the console output comes from my custom DayComponent, and is just dumping out the events that are passed to it. 

![image](https://github.com/bruceharrison1984/Schedulely/assets/25244878/6d91de2a-6740-403b-b372-89b9a683d60e)
Having removed one event via filtering, it correctly shows just the one event in the calendar, but the DayComponent has two events passed through, which includes one that has been removed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: Chrome

**Smartphone (please complete the following information):**
 - Version [e.g. 22]: 114

**Additional context**
I haven't dug too much into this, but initial suspicions are with this code
https://github.com/bruceharrison1984/Schedulely/blob/main/packages/Schedulely/src/providers/EventIntersectionProvider.tsx#L42-L48

The WeekLayout uses the `getEventsOnDate` function from the `useEventIntersection()` hook, that function (as linked above), uses the `isDateBetween` function from the DateAdaptor, however, it's just checking the events that are in `eventVisibility` which I think isn't updated when the list of events passed through has changed and the month hasn't.

**Comment by scottlovegrove** [comment]
Weirdly, I have just tried replicating this with the Storybook, and it's not reproducing 🤔 So not sure why my custom day component is not behaving in the same way.

**Comment by scottlovegrove** [comment]
I have a repro for the secondary events issue mentioned in the above commit. If you look at this commit on my branch https://github.com/scottlovegrove/Schedulely/commit/d8ee1681c3f7ca5c0d4d5e619d7902906d7270c6, before you even toggle the filter button in the story, looking at the console, filter for the day that is today, and you can see that all three events are passed through into the day component, even though one of them is _not_ for that day. 

I hope this makes sense.

**Comment by bruceharrison1984** [comment]
That certainly sounds like something is definitely wrong here. I'll see if I can make some time to take a look this week.
