### ISSUE TITLE
OnDayClick not triggered if there are events for the week on other days

### ISSUE THREAD

**Issue by scottlovegrove** [bruceharrison1984/Schedulely#96]
**Describe the bug**
So this could be quite a problematic bug I'm afraid.

If you have events for a day, when those events are rendered, if you try clicking on a day that doesn't have an event, the `onDayClick` eventHandler isn't fired _if_ you clicked parrallel to the events. If you click lower down in the day _below_ where the events finish getting rendered, then the `onDayClick` eventHandler _is_ fired.

**To Reproduce**
Pull down my branch for this commit https://github.com/scottlovegrove/Schedulely/commit/8604a6983b8bf2d5e398ad8e9ee19a8c55a53b4a, there is a story called `OnDayClickBug`

![image](https://github.com/bruceharrison1984/Schedulely/assets/25244878/ef1436de-f46b-427d-add4-778fac60142f)

This is made even worse on mobile because you may not have the abundance of space seen in the screenshot, effectively making the onDayClick event completely useless.

**Expected behavior**
The `onDayClick` event should get triggered when it's clicked (I will concede it shouldn't if you have actually clicked on an event). 

**Additional context**
As it happens, I've managed to get around this issue in my own app because I don't care if the user clicks on an actual event, so I've just added this to my css
```css
.schedulely .event-week-layout {
    pointer-events: none;
}
```

**Comment by bruceharrison1984** [comment]
Yes, that one will be tricky. The way the grid is overlayed on top of the calendar means that onClick handlers won't propagate through directly to the day component.

Hopefully I can get around to this quickly. I just took on a new client so I don't have a ton of bandwidth ATM.

**Comment by scottlovegrove** [comment]
> Hopefully I can get around to this quickly. I just took on a new client so I don't have a ton of bandwidth ATM.

From my perspective, that's fine, as mentioned, I don't need users to be able to click on individual events, so I just bypass the events row completely :) I was just logging the bug while I thought about it because it will likely affect some users at some point.

**Comment by bruceharrison1984** [comment]
Well I appreciate the issue submissions! I'm wondering if some CSS trickery can get around this, or potentially merge the event grid with the day of week grid. This wasn't completely surprising, because I knew there were some staking issues related to this.

**Comment by bruceharrison1984** [comment]
This was easily fixed by disabling `pointer-events` on the grid itself, and then re-enabling them for all child divs. This could cause issues if someone tries to using something other than a div to contain a custom event, but the answer would then be to just use a div.
